spring:
  datasource:
    url: jdbc:mysql://localhost:3306/device_manufacture_db
    username: default
    password: default
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always
      platform: dev