version: '3.8'
services:
  db:
    image: mysql:8.0.29
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=quotes
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - device-manufacture-db:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d/:ro
volumes:
  device-manufacture-db: